name: 632 error

on:
  workflow_dispatch:

jobs:
  build_android:
    name: Build Java
    runs-on: self-hosted
    steps:
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.0
      with:
        distribution: 'oracle'
        java-version: 17.0.11
        check-latest: false
        cache: 'maven'
